CREATE TABLE PIZZA_RECIPES_CLEAN 
SELECT pizza_id,
       CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(toppings, ',', n), ',', -1) AS UNSIGNED) AS topping
FROM pizza_recipes
JOIN (
    SELECT 1 AS n UNION ALL
    SELECT 2 UNION ALL
    SELECT 3 UNION ALL
    SELECT 4 UNION ALL
    SELECT 5 UNION ALL
    SELECT 6 UNION ALL
    SELECT 7 UNION ALL
    SELECT 8 UNION ALL
    SELECT 9 UNION ALL
    SELECT 10
) numbers
ON CHAR_LENGTH(toppings) - CHAR_LENGTH(REPLACE(toppings, ',', '')) >= n - 1
ORDER BY pizza_id, n;
